export interface AIServiceData {
  name: string;
  company: string;
  category: string;
  region: string;
  hqTimezone: string;
  website: string;
  downdetectorUrl?: string;
  peakHoursStart: number;
  peakHoursEnd: number;
  secondaryPeakStart: number;
  secondaryPeakEnd: number;
  riskLevel: "high" | "medium" | "low";
}

export const AI_SERVICES: AIServiceData[] = [
  // Category: LLM (Large Language Models)
  {
    name: "ChatGPT",
    company: "OpenAI",
    category: "LLM",
    region: "US",
    hqTimezone: "America/New_York",
    website: "https://chat.openai.com",
    downdetectorUrl: "https://downdetector.com/status/chatgpt/",
    peakHoursStart: 9,
    peakHoursEnd: 12,
    secondaryPeakStart: 19,
    secondaryPeakEnd: 22,
    riskLevel: "high",
  },
  {
    name: "Gemini",
    company: "Google",
    category: "LLM",
    region: "US",
    hqTimezone: "America/Los_Angeles",
    website: "https://gemini.google.com",
    downdetectorUrl: "https://downdetector.com/status/google-gemini/",
    peakHoursStart: 9,
    peakHoursEnd: 12,
    secondaryPeakStart: 19,
    secondaryPeakEnd: 22,
    riskLevel: "high",
  },
  {
    name: "Claude",
    company: "Anthropic",
    category: "LLM",
    region: "US",
    hqTimezone: "America/Los_Angeles",
    website: "https://claude.ai",
    downdetectorUrl: "https://downdetector.com/status/claude-ai/",
    peakHoursStart: 9,
    peakHoursEnd: 12,
    secondaryPeakStart: 19,
    secondaryPeakEnd: 22,
    riskLevel: "high",
  },
  {
    name: "Meta AI",
    company: "Meta",
    category: "LLM",
    region: "US",
    hqTimezone: "America/Los_Angeles",
    website: "https://meta.ai",
    peakHoursStart: 9,
    peakHoursEnd: 13,
    secondaryPeakStart: 20,
    secondaryPeakEnd: 23,
    riskLevel: "medium",
  },
  {
    name: "Mistral / Le Chat",
    company: "Mistral AI",
    category: "LLM",
    region: "EU",
    hqTimezone: "Europe/Paris",
    website: "https://chat.mistral.ai",
    downdetectorUrl: "https://downdetector.com/status/mistral-ai/",
    peakHoursStart: 9,
    peakHoursEnd: 12,
    secondaryPeakStart: 19,
    secondaryPeakEnd: 22,
    riskLevel: "medium",
  },
  {
    name: "DeepSeek",
    company: "DeepSeek AI",
    category: "LLM",
    region: "CN",
    hqTimezone: "Asia/Shanghai",
    website: "https://chat.deepseek.com",
    peakHoursStart: 9,
    peakHoursEnd: 12,
    secondaryPeakStart: 20,
    secondaryPeakEnd: 23,
    riskLevel: "high",
  },
  {
    name: "Kimi",
    company: "Moonshot AI",
    category: "LLM",
    region: "CN",
    hqTimezone: "Asia/Shanghai",
    website: "https://kimi.moonshot.cn",
    peakHoursStart: 9,
    peakHoursEnd: 12,
    secondaryPeakStart: 20,
    secondaryPeakEnd: 23,
    riskLevel: "medium",
  },
  {
    name: "Qwen",
    company: "Alibaba Cloud",
    category: "LLM",
    region: "CN",
    hqTimezone: "Asia/Shanghai",
    website: "https://tongyi.aliyun.com",
    peakHoursStart: 9,
    peakHoursEnd: 12,
    secondaryPeakStart: 20,
    secondaryPeakEnd: 23,
    riskLevel: "medium",
  },
  {
    name: "Grok",
    company: "xAI",
    category: "LLM",
    region: "US",
    hqTimezone: "America/New_York",
    website: "https://grok.x.ai",
    peakHoursStart: 9,
    peakHoursEnd: 12,
    secondaryPeakStart: 19,
    secondaryPeakEnd: 22,
    riskLevel: "high",
  },
  {
    name: "Pi",
    company: "Inflection AI",
    category: "LLM",
    region: "US",
    hqTimezone: "America/Los_Angeles",
    website: "https://pi.ai",
    peakHoursStart: 9,
    peakHoursEnd: 12,
    secondaryPeakStart: 19,
    secondaryPeakEnd: 22,
    riskLevel: "low",
  },
  {
    name: "Zhipu AI / GLM",
    company: "Zhipu",
    category: "LLM",
    region: "CN",
    hqTimezone: "Asia/Shanghai",
    website: "https://chatglm.cn",
    peakHoursStart: 9,
    peakHoursEnd: 12,
    secondaryPeakStart: 20,
    secondaryPeakEnd: 23,
    riskLevel: "medium",
  },
  {
    name: "Character.ai",
    company: "Character.ai",
    category: "LLM",
    region: "US",
    hqTimezone: "America/Los_Angeles",
    website: "https://character.ai",
    downdetectorUrl: "https://downdetector.com/status/character-ai/",
    peakHoursStart: 18,
    peakHoursEnd: 23,
    secondaryPeakStart: 12,
    secondaryPeakEnd: 15,
    riskLevel: "high",
  },

  // Category: Research
  {
    name: "Perplexity AI",
    company: "Perplexity",
    category: "Research",
    region: "US",
    hqTimezone: "America/Los_Angeles",
    website: "https://perplexity.ai",
    downdetectorUrl: "https://downdetector.com/status/perplexity-ai/",
    peakHoursStart: 9,
    peakHoursEnd: 12,
    secondaryPeakStart: 19,
    secondaryPeakEnd: 22,
    riskLevel: "medium",
  },
  {
    name: "You.com",
    company: "You.com",
    category: "Research",
    region: "US",
    hqTimezone: "America/Los_Angeles",
    website: "https://you.com",
    peakHoursStart: 9,
    peakHoursEnd: 12,
    secondaryPeakStart: 19,
    secondaryPeakEnd: 22,
    riskLevel: "low",
  },
  {
    name: "Genspark",
    company: "Genspark",
    category: "Research",
    region: "US",
    hqTimezone: "America/Los_Angeles",
    website: "https://genspark.ai",
    peakHoursStart: 9,
    peakHoursEnd: 12,
    secondaryPeakStart: 19,
    secondaryPeakEnd: 22,
    riskLevel: "low",
  },
  {
    name: "Phind",
    company: "Phind",
    category: "Research",
    region: "US",
    hqTimezone: "America/Los_Angeles",
    website: "https://phind.com",
    peakHoursStart: 9,
    peakHoursEnd: 13,
    secondaryPeakStart: 20,
    secondaryPeakEnd: 23,
    riskLevel: "low",
  },
  {
    name: "Consensus",
    company: "Consensus",
    category: "Research",
    region: "US",
    hqTimezone: "America/New_York",
    website: "https://consensus.app",
    peakHoursStart: 9,
    peakHoursEnd: 12,
    secondaryPeakStart: 19,
    secondaryPeakEnd: 22,
    riskLevel: "low",
  },
  {
    name: "Elicit",
    company: "Elicit",
    category: "Research",
    region: "US",
    hqTimezone: "America/Los_Angeles",
    website: "https://elicit.com",
    peakHoursStart: 9,
    peakHoursEnd: 12,
    secondaryPeakStart: 19,
    secondaryPeakEnd: 22,
    riskLevel: "low",
  },

  // Category: Image
  {
    name: "Midjourney",
    company: "Midjourney",
    category: "Image",
    region: "US",
    hqTimezone: "America/Los_Angeles",
    website: "https://midjourney.com",
    downdetectorUrl: "https://downdetector.com/status/midjourney/",
    peakHoursStart: 9,
    peakHoursEnd: 13,
    secondaryPeakStart: 19,
    secondaryPeakEnd: 23,
    riskLevel: "high",
  },
  {
    name: "DALL-E 3",
    company: "OpenAI",
    category: "Image",
    region: "US",
    hqTimezone: "America/New_York",
    website: "https://openai.com/dall-e-3",
    peakHoursStart: 9,
    peakHoursEnd: 12,
    secondaryPeakStart: 19,
    secondaryPeakEnd: 22,
    riskLevel: "high",
  },
  {
    name: "Adobe Firefly",
    company: "Adobe",
    category: "Image",
    region: "US",
    hqTimezone: "America/Los_Angeles",
    website: "https://firefly.adobe.com",
    peakHoursStart: 9,
    peakHoursEnd: 13,
    secondaryPeakStart: 19,
    secondaryPeakEnd: 22,
    riskLevel: "medium",
  },
  {
    name: "Canva Magic Studio",
    company: "Canva",
    category: "Image",
    region: "AU",
    hqTimezone: "Australia/Sydney",
    website: "https://canva.com",
    downdetectorUrl: "https://downdetector.com/status/canva/",
    peakHoursStart: 9,
    peakHoursEnd: 12,
    secondaryPeakStart: 19,
    secondaryPeakEnd: 22,
    riskLevel: "low",
  },
  {
    name: "Leonardo.ai",
    company: "Leonardo",
    category: "Image",
    region: "US",
    hqTimezone: "America/Los_Angeles",
    website: "https://leonardo.ai",
    peakHoursStart: 9,
    peakHoursEnd: 13,
    secondaryPeakStart: 19,
    secondaryPeakEnd: 23,
    riskLevel: "medium",
  },
  {
    name: "Playground AI",
    company: "Playground",
    category: "Image",
    region: "US",
    hqTimezone: "America/Los_Angeles",
    website: "https://playground.ai",
    peakHoursStart: 9,
    peakHoursEnd: 12,
    secondaryPeakStart: 19,
    secondaryPeakEnd: 22,
    riskLevel: "low",
  },
  {
    name: "Stability AI",
    company: "Stability AI",
    category: "Image",
    region: "EU",
    hqTimezone: "Europe/London",
    website: "https://stability.ai",
    peakHoursStart: 9,
    peakHoursEnd: 12,
    secondaryPeakStart: 19,
    secondaryPeakEnd: 22,
    riskLevel: "medium",
  },
  {
    name: "Microsoft Designer",
    company: "Microsoft",
    category: "Image",
    region: "US",
    hqTimezone: "America/Los_Angeles",
    website: "https://designer.microsoft.com",
    peakHoursStart: 9,
    peakHoursEnd: 13,
    secondaryPeakStart: 19,
    secondaryPeakEnd: 22,
    riskLevel: "medium",
  },
  {
    name: "Ideogram",
    company: "Ideogram",
    category: "Image",
    region: "CA",
    hqTimezone: "America/Toronto",
    website: "https://ideogram.ai",
    peakHoursStart: 9,
    peakHoursEnd: 12,
    secondaryPeakStart: 19,
    secondaryPeakEnd: 22,
    riskLevel: "medium",
  },
  {
    name: "Looka",
    company: "Looka",
    category: "Image",
    region: "CA",
    hqTimezone: "America/Toronto",
    website: "https://looka.com",
    peakHoursStart: 9,
    peakHoursEnd: 12,
    secondaryPeakStart: 19,
    secondaryPeakEnd: 22,
    riskLevel: "low",
  },

  // Category: Video
  {
    name: "Runway (Gen-3)",
    company: "Runway",
    category: "Video",
    region: "US",
    hqTimezone: "America/New_York",
    website: "https://runwayml.com",
    downdetectorUrl: "https://downdetector.com/status/runway-ml/",
    peakHoursStart: 9,
    peakHoursEnd: 13,
    secondaryPeakStart: 19,
    secondaryPeakEnd: 23,
    riskLevel: "high",
  },
  {
    name: "Luma Dream Machine",
    company: "Luma AI",
    category: "Video",
    region: "US",
    hqTimezone: "America/Los_Angeles",
    website: "https://lumalabs.ai",
    peakHoursStart: 9,
    peakHoursEnd: 13,
    secondaryPeakStart: 19,
    secondaryPeakEnd: 23,
    riskLevel: "high",
  },
  {
    name: "Kling AI",
    company: "Kuaishou",
    category: "Video",
    region: "CN",
    hqTimezone: "Asia/Shanghai",
    website: "https://klingai.com",
    peakHoursStart: 9,
    peakHoursEnd: 12,
    secondaryPeakStart: 20,
    secondaryPeakEnd: 23,
    riskLevel: "medium",
  },
  {
    name: "Pika Labs",
    company: "Pika",
    category: "Video",
    region: "US",
    hqTimezone: "America/Los_Angeles",
    website: "https://pika.art",
    peakHoursStart: 9,
    peakHoursEnd: 13,
    secondaryPeakStart: 19,
    secondaryPeakEnd: 23,
    riskLevel: "medium",
  },
  {
    name: "HeyGen",
    company: "HeyGen",
    category: "Video",
    region: "US",
    hqTimezone: "America/Los_Angeles",
    website: "https://heygen.com",
    peakHoursStart: 9,
    peakHoursEnd: 12,
    secondaryPeakStart: 19,
    secondaryPeakEnd: 22,
    riskLevel: "medium",
  },
  {
    name: "Synthesia",
    company: "Synthesia",
    category: "Video",
    region: "EU",
    hqTimezone: "Europe/London",
    website: "https://synthesia.io",
    peakHoursStart: 9,
    peakHoursEnd: 12,
    secondaryPeakStart: 19,
    secondaryPeakEnd: 22,
    riskLevel: "medium",
  },
  {
    name: "Sora",
    company: "OpenAI",
    category: "Video",
    region: "US",
    hqTimezone: "America/New_York",
    website: "https://openai.com/sora",
    peakHoursStart: 9,
    peakHoursEnd: 13,
    secondaryPeakStart: 19,
    secondaryPeakEnd: 23,
    riskLevel: "high",
  },

  // Category: Writing
  {
    name: "Jasper",
    company: "Jasper",
    category: "Writing",
    region: "US",
    hqTimezone: "America/Chicago",
    website: "https://jasper.ai",
    peakHoursStart: 9,
    peakHoursEnd: 12,
    secondaryPeakStart: 19,
    secondaryPeakEnd: 22,
    riskLevel: "medium",
  },
  {
    name: "Copy.ai",
    company: "Copy.ai",
    category: "Writing",
    region: "US",
    hqTimezone: "America/Los_Angeles",
    website: "https://copy.ai",
    peakHoursStart: 9,
    peakHoursEnd: 12,
    secondaryPeakStart: 19,
    secondaryPeakEnd: 22,
    riskLevel: "low",
  },
  {
    name: "Writesonic",
    company: "Writesonic",
    category: "Writing",
    region: "US",
    hqTimezone: "America/Los_Angeles",
    website: "https://writesonic.com",
    peakHoursStart: 9,
    peakHoursEnd: 12,
    secondaryPeakStart: 19,
    secondaryPeakEnd: 22,
    riskLevel: "low",
  },
  {
    name: "Notion AI",
    company: "Notion",
    category: "Writing",
    region: "US",
    hqTimezone: "America/Los_Angeles",
    website: "https://notion.so",
    downdetectorUrl: "https://downdetector.com/status/notion/",
    peakHoursStart: 9,
    peakHoursEnd: 12,
    secondaryPeakStart: 19,
    secondaryPeakEnd: 22,
    riskLevel: "medium",
  },
  {
    name: "Grammarly",
    company: "Grammarly",
    category: "Writing",
    region: "US",
    hqTimezone: "America/Los_Angeles",
    website: "https://grammarly.com",
    downdetectorUrl: "https://downdetector.com/status/grammarly/",
    peakHoursStart: 9,
    peakHoursEnd: 12,
    secondaryPeakStart: 19,
    secondaryPeakEnd: 22,
    riskLevel: "low",
  },
  {
    name: "Rytr",
    company: "Rytr",
    category: "Writing",
    region: "IN",
    hqTimezone: "Asia/Kolkata",
    website: "https://rytr.me",
    peakHoursStart: 9,
    peakHoursEnd: 13,
    secondaryPeakStart: 19,
    secondaryPeakEnd: 22,
    riskLevel: "low",
  },
  {
    name: "Gamma",
    company: "Gamma",
    category: "Writing",
    region: "US",
    hqTimezone: "America/Los_Angeles",
    website: "https://gamma.app",
    peakHoursStart: 9,
    peakHoursEnd: 12,
    secondaryPeakStart: 19,
    secondaryPeakEnd: 22,
    riskLevel: "low",
  },

  // Category: Coding
  {
    name: "GitHub Copilot",
    company: "GitHub",
    category: "Coding",
    region: "US",
    hqTimezone: "America/Los_Angeles",
    website: "https://github.com/features/copilot",
    downdetectorUrl: "https://downdetector.com/status/github/",
    peakHoursStart: 9,
    peakHoursEnd: 13,
    secondaryPeakStart: 20,
    secondaryPeakEnd: 23,
    riskLevel: "medium",
  },
  {
    name: "Cursor",
    company: "Cursor",
    category: "Coding",
    region: "US",
    hqTimezone: "America/Los_Angeles",
    website: "https://cursor.sh",
    peakHoursStart: 9,
    peakHoursEnd: 13,
    secondaryPeakStart: 20,
    secondaryPeakEnd: 23,
    riskLevel: "high",
  },
  {
    name: "Replit Agent",
    company: "Replit",
    category: "Coding",
    region: "US",
    hqTimezone: "America/Los_Angeles",
    website: "https://replit.com",
    peakHoursStart: 9,
    peakHoursEnd: 13,
    secondaryPeakStart: 20,
    secondaryPeakEnd: 23,
    riskLevel: "medium",
  },
  {
    name: "Codeium",
    company: "Codeium",
    category: "Coding",
    region: "US",
    hqTimezone: "America/Los_Angeles",
    website: "https://codeium.com",
    peakHoursStart: 9,
    peakHoursEnd: 13,
    secondaryPeakStart: 20,
    secondaryPeakEnd: 23,
    riskLevel: "low",
  },

  // Category: Audio
  {
    name: "Suno AI",
    company: "Suno",
    category: "Audio",
    region: "US",
    hqTimezone: "America/Los_Angeles",
    website: "https://suno.com",
    downdetectorUrl: "https://downdetector.com/status/suno-ai/",
    peakHoursStart: 9,
    peakHoursEnd: 13,
    secondaryPeakStart: 19,
    secondaryPeakEnd: 23,
    riskLevel: "high",
  },
  {
    name: "Udio",
    company: "Udio",
    category: "Audio",
    region: "US",
    hqTimezone: "America/New_York",
    website: "https://udio.com",
    peakHoursStart: 9,
    peakHoursEnd: 13,
    secondaryPeakStart: 19,
    secondaryPeakEnd: 23,
    riskLevel: "high",
  },
  {
    name: "ElevenLabs",
    company: "ElevenLabs",
    category: "Audio",
    region: "US",
    hqTimezone: "America/New_York",
    website: "https://elevenlabs.io",
    peakHoursStart: 9,
    peakHoursEnd: 12,
    secondaryPeakStart: 19,
    secondaryPeakEnd: 22,
    riskLevel: "medium",
  },
  {
    name: "AIVA",
    company: "AIVA",
    category: "Audio",
    region: "LU",
    hqTimezone: "Europe/Luxembourg",
    website: "https://aiva.ai",
    peakHoursStart: 9,
    peakHoursEnd: 12,
    secondaryPeakStart: 19,
    secondaryPeakEnd: 22,
    riskLevel: "low",
  },
];

export const CATEGORIES = ["LLM", "Research", "Image", "Video", "Writing", "Coding", "Audio"] as const;
export type Category = (typeof CATEGORIES)[number];

export const REGIONS = [
  { value: "all", label: "Todos" },
  { value: "US", label: "🇺🇸 Américas" },
  { value: "EU", label: "🇪🇺 Europa" },
  { value: "CN", label: "🇨🇳 Ásia" },
  { value: "AU", label: "🇦🇺 Oceania" },
  { value: "CA", label: "🇨🇦 Canadá" },
  { value: "IN", label: "🇮🇳 Índia" },
  { value: "LU", label: "🇱🇺 Luxemburgo" },
] as const;

export const REGION_FLAGS: Record<string, string> = {
  US: "🇺🇸",
  EU: "🇪🇺",
  CN: "🇨🇳",
  AU: "🇦🇺",
  CA: "🇨🇦",
  IN: "🇮🇳",
  LU: "🇱🇺",
};

export const CATEGORY_LABELS: Record<Category, string> = {
  LLM: "LLMs",
  Research: "Pesquisa",
  Image: "Imagem",
  Video: "Vídeo",
  Writing: "Escrita",
  Coding: "Código",
  Audio: "Áudio",
};

export const CATEGORY_ICONS: Record<Category, string> = {
  LLM: "Brain",
  Research: "Search",
  Image: "Image",
  Video: "Video",
  Writing: "PenTool",
  Coding: "Code",
  Audio: "Music",
};
